var express = require('express')
var bcrypt = require('bcrypt')
var cors = require('cors')
var path = require('path')
require('dotenv').config()
var db = require('./config/dbConnnection')
const authRouter = require('./route/authRouter')
const taskRouter = require('./route/taskRouter')
const app = express()
app.use(cors())
app.use(express.json())
app.use(express.urlencoded({extended:true}))

app.use('/auth',authRouter)
app.use('/task',taskRouter)
app.listen(4000,()=>{console.log("Port Listened Successfully ");})